### PR TITLE
feat: searching spaces and getting proposals of that space

### PR DESCRIPTION
**Pull request by miralsuthar**
https://www.loom.com/share/0d18e2d98b6a4c5c82074ebe6a41ac50

Create a feature that search for spaces and when you click on particular space it redirect you to the list of proposals that space contains

### CODE REVIEW

**Comment by kempsterrrr** [comment]
Awesome start man!!!!

Some thoughts here in Loom - https://www.loom.com/share/e2b5ea42dc4f49d5ab08fbd26e8a2ba5

Summarised as :

- Can we control the order of the list of all Spaces in the first view (i.e. by number of folloers/members)
- Can we update the search so folks don't need to know the Space's ENS name to find it. If not, maybe we can either tell the user in the UI they need to search via the ENS name OR we can just secretly add `.eth` to the end of their search term in the extensions code.

Let me know what you think !!!

Haven't had a chance to check the CODE yet but will take a look tomorrow 🤝

**Comment by miralsuthar** [comment]
https://www.loom.com/share/2da1d9152a3d49f795e8204b7a529287

**Comment by kempsterrrr** [comment]
Nice @miralsuthar !!! Loving that. I'll be back online this afternoon, pulling down the code, and taking a look.

Did you have any luck with ordering the spaces in the first view?

If the API can't support it maybe we can just do a manual filter in code after we receive the data from the API (i.e. write a JS function that re-orders the array based on a value of each item)

smashing it mate.

**Comment by kempsterrrr** [comment]
Closes #1

**Pull request merged**
